// Copyright (C) 2016  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Intel and sold by Intel or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus Prime Version 16.1 (Build Build 196 10/24/2016)
// Created on Wed Dec 28 17:26:12 2016

ComputeEnergy ComputeEnergy_inst
(
	.clock(clock_sig) ,	// input  clock_sig
	.sample_data(sample_data_sig) ,	// input [SAMPLE_WIDTH-1:0] sample_data_sig
	.sample_valid(sample_valid_sig) ,	// input  sample_valid_sig
	.sample_ready(sample_ready_sig) ,	// output  sample_ready_sig
	.energy_data(energy_data_sig) ,	// output [ENERGY_WIDTH-1:0] energy_data_sig
	.energy_valid(energy_valid_sig) ,	// output  energy_valid_sig
	.energy_ready(energy_ready_sig) 	// input  energy_ready_sig
);

defparam ComputeEnergy_inst.SAMPLE_WIDTH = 16;
defparam ComputeEnergy_inst.ENERGY_WIDTH = 32;
defparam ComputeEnergy_inst.DURATION = 16;
defparam ComputeEnergy_inst.LAG = 15;
