// Copyright (C) 2016  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Intel and sold by Intel or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus Prime Version 16.1 (Build Build 196 10/24/2016)
// Created on Fri Dec 30 13:32:36 2016

ToggleLight ToggleLight_inst
(
	.clock(clock_sig) ,	// input  clock_sig
	.claps_data(claps_data_sig) ,	// input [CLAPS_WIDTH-1:0] claps_data_sig
	.claps_valid(claps_valid_sig) ,	// input  claps_valid_sig
	.claps_ready(claps_ready_sig) ,	// output  claps_ready_sig
	.toglite_state(toglite_state_sig) 	// output  toglite_state_sig
);

defparam ToggleLight_inst.CLAPS_WIDTH = 16;
defparam ToggleLight_inst.TOGLITE_ON_VAL = 2;
defparam ToggleLight_inst.TOGLITE_OFF_VAL = 3;
